apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-tenantb-to-tenanta
  namespace: tenantb
spec:
  selector:
    matchLabels:
      app: httpd
  action: DENY
  rules:
  - to:
    - operation:
        hosts: ["*"]
        namespaces: ["tenanta"]
