apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: tenanta
spec:
  podSelector: {} # Select all pods in the namespace
  policyTypes:
  - Ingress
  - Egress
